site_name: 'Binary Ninja User Documentation'
site_description: 'Documentation for the Binary Ninja reverse engineering platform'
site_author: 'Vector 35 Inc'
copyright: '(<a href="https://creativecommons.org/licenses/by/3.0/">cc</a>) <a href="https://vector35.com/">Vector 35 Inc</a>'
dev_addr: 0.0.0.0:8000
site_url: 'https://docs.binary.ninja/'
repo_url: 'https://binary.ninja/'
repo_name: 'binary.ninja'
use_directory_urls: false
extra_css: ['docs.css', 'github.min.css', 'juxtapose.min.css']
extra_javascript: ['highlight.min.js', 'cpp.min.js', 'python.min.js', 'juxtapose.min.js', 'tabsync.js']

theme:
    name: material
    custom_dir: overrides
    favicon: 'img/favicon.ico'
    font: false
    highlightjs: false
    palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: binja
      accent: red
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes # Consider revisiting this later if top-levels being clickable isn't obvious
        - navigation.top
        - content.code.copy
        - search.highlight
        - toc.follow

    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 191   # ? / /

plugins:
    - search:
        lang: en
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - offline
    - privacy
    - glightbox:
        background: none
        shadow: false
    - htmlproofer:
        enabled: !ENV [VALIDATE, False]
    - redirects:
        redirect_maps:
            'index.md': 'getting-started.md'
            'guide/debugger.md': 'guide/debugger/index.md'
            'guide/remote-debugging.md': 'guide/debugger/remote-debugging.md'
            'guide/dbgeng-ttd.md': 'guide/debugger/dbgeng-ttd.md'

markdown_extensions:
    - attr_list
    - md_in_html
    - codehilite
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
        permalink: True

nav:
    - User Documentation:
        - Getting Started: 'getting-started.md'
        - User Guide:
          - 'guide/index.md'
          - Using Plugins: 'guide/plugins.md'
          - Settings: 'guide/settings.md'
          - Projects: 'guide/projects.md'
          - Enterprise: 'guide/enterprise/index.md'
          - Troubleshooting: 'guide/troubleshooting.md'
          - Objective-C: 'guide/objectivec.md'
          - Firmware Ninja: 'guide/firmwareninja.md'
          - Shared Cache: 'guide/sharedcache.md'
          - Kernel Cache: 'guide/kernelcache.md'
          - EFI Resolver: 'guide/efiresolver.md'
          - WARP: 'guide/warp.md'
          - BinExport / BinDiff: 'guide/binexport.md'
          - Guided Analysis: 'guide/guided_analysis.md'
        - Debugger:
            - Overview: 'guide/debugger/index.md'
            - Remote Debugging: 'guide/debugger/remote-debugging.md'
            - Time Travel Debugging (Windows): 'guide/debugger/dbgeng-ttd.md'
            - Time Travel Debugging (Linux): 'guide/debugger/gdbrsp-ttd.md'
            - Kernel Debugging (Windows): 'guide/debugger/windows-kd.md'
            - Corellium Remote Debugging: 'guide/debugger/corellium-remote-debugging.md'
        - Migration Guide:
            - 'guide/migration/index.md'
            - Migrating from IDA: 'guide/migration/migrationguideida.md'
            - Migrating from Ghidra: 'guide/migration/migrationguideghidra.md'
        - Types:
            - 'guide/types/index.md'
            - Basic Types: 'guide/types/basictypes.md'
            - Working With Types: 'guide/types/type.md'
            - Type Attributes and Annotations: 'guide/types/attributes.md'
            - Importing/Exporting Types: 'guide/types/typeimportexport.md'
            - Type Archives: 'guide/types/typearchives.md'
            - Type Libraries: 'guide/types/typelibraries.md'
            - Debug Info: 'guide/types/debuginfo.md'
            - Platform Types: 'guide/types/platformtypes.md'
            - C++ Types: 'guide/types/cpp.md'
    - Developer Documentation:
        - 'dev/index.md'
        - Cookbook: 'dev/cookbook.md'
        - Writing Plugins: 'dev/plugins.md'
        - Automation: 'dev/batch.md'
        - BNIL / Architectures:
            - BNIL Guide&#58; Overview: 'dev/bnil-overview.md'
            - BNIL Guide&#58; LLIL: 'dev/bnil-llil.md'
            - BNIL Guide&#58; MLIL: 'dev/bnil-mlil.md'
            - BNIL Guide&#58; HLIL: 'dev/bnil-hlil.md'
            - Flag Guide: 'dev/flags.md'
            - Modifying ILs: 'dev/bnil-modifying.md'
        - Types:
            - Applying Annotations: 'dev/annotation.md'
            - Type Libraries: 'dev/typelibraries.md'
        - Important Concepts:
            - 'dev/concepts.md'
            - User Informed Data Flow: 'dev/uidf.md'
            - Workflows: 'dev/workflows.md'
        - Creating Themes: 'dev/themes.md'
        - Contributing Documentation: 'dev/documentation.md'
    - About:
        - 'about/index.md'
        - License: 'about/license.md'
        - Open Source: 'about/open-source.md'
        - Icons: 'about/icons.md'

extra:
    disablesearch: True
    logo: 'images/logo.png'
