blank_issues_enabled: false
contact_links:
  - name: Binary Ninja Slack
    url: https://slack.binary.ninja/
    about: Join for quick responses to short questions
  - name: Official Support
    url: https://binary.ninja/support/
    about: Check our official support page for more information
