[package]
name = "arch_msp430"
version = "0.1.0"
authors = ["jrozner"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
binaryninja.workspace = true
binaryninjacore-sys.workspace = true
log = "0.4"
msp430-asm = "^0.2"

[lib]
crate-type = ["cdylib"]
